import Navbar from "@/components/Shared/Navbar";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { DM_Sans } from "next/font/google";
import Footer from "@/components/Shared/Footer";
import AnimatedCursor from "@/components/libs/AnimatedCursor";
import { CursorProvider } from "@/components/libs/Context/CursorContext";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
  variable: "--font-dm-sans",
});

export const metadata = {
  title: "Go Connecte Website",
  description: "Generated by Next.js, Tailwind CSS, and Material UI",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={dmSans.className}>
      <body>
        <CursorProvider>
          <AnimatedCursor borderColor="white" />
          <Navbar />
          {children}
          <Footer />
        </CursorProvider>
      </body>
    </html>
  );
}
