import Navbar from "@/components/Shared/Navbar";
import "./globals.css";
import { DM_Sans } from "next/font/google";
import Footer from "@/components/Shared/Footer";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
  variable: "--font-dm-sans",
});

export const metadata = {
  title: "Go Connecte Website",
  description: "Generated by Next.js, Tailwind CSS, and Material UI",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={dmSans.className}>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
